version: '3'
services:
  db:
    container_name: TrendToDo-db
    build:
      dockerfile: docker/db/Dockerfile
      context: .
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - ./api/.env
    ports:
      - "3306:3306"
    networks:
      - app-net

  api:
    container_name: TrendToDo-api
    build:
      dockerfile: docker/api/Dockerfile
      context: .
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ./
        target: /app
    # command: python ./api/main.py
    command: /bin/sh
    networks:
      - app-net
    depends_on:
      - db
    tty: true

volumes:
  db_data:

networks:
  app-net:
    driver: bridge